name: 'install-cocoapods-action'
description: 'Install or cache cocoapods'
branding:
  icon: 'arrow-up-circle'
  color: 'green'

# TODO: Specify version

runs:
  using: "composite"
  steps:
    - name: Cache pod lib
      id: cache-pod-lib
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/pod
        key: ${{ runner.os }}-pod-lib-v1

    - name: Install cocoapods
      if: steps.cache-pod-lib.outputs.cache-hit != 'true'
      run: |
        export GEM_HOME=$HOME/.gem
        export PATH=$GEM_HOME/bin:$PATH
        gem install -n /usr/local/bin cocoapods
      shell: bash
